import { createRequestHandler } from "react-router";
import {
  attachMaindataWebSocket,
  MAINDATA_WS_PATH,
  maindataHub,
} from "./app/lib/qb-maindata-hub";

process.env.NODE_ENV ??= "production";

// Generated by `bun run build` — stub types when the folder is absent in dev.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error — no declarations until first production build
const build = await import("./build/server/index.js");
const requestHandler = createRequestHandler(build);

type WsData = {
  cleanup?: () => void;
};

maindataHub.start();

const server = Bun.serve<WsData>({
  port: Number(process.env.PORT) || 3000,
  async fetch(request, bunServer) {
    const url = new URL(request.url);
    if (url.pathname === MAINDATA_WS_PATH) {
      const upgraded = bunServer.upgrade(request, {
        data: {} as WsData,
      });
      if (upgraded) return undefined as unknown as Response;
      return new Response("Expected WebSocket", { status: 426 });
    }

    const staticPath = `./build/client${url.pathname}`;
    const file = Bun.file(staticPath);
    if (await file.exists()) {
      return new Response(file);
    }
    return requestHandler(request);
  },
  websocket: {
    open(ws) {
      ws.data.cleanup = attachMaindataWebSocket(ws);
    },
    message() {
      // Client → server messages are ignored (server pushes only).
    },
    close(ws) {
      ws.data.cleanup?.();
      ws.data.cleanup = undefined;
    },
  },
});

console.log(`Server running on http://localhost:${server.port}`);
console.log(
  `Maindata WebSocket at ws://localhost:${server.port}${MAINDATA_WS_PATH}`,
);
