// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/library": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/torrents": {
    params: {};
  };
  "/debug/liquid-glass": {
    params: {};
  };
  "/debug/liquid-glass-controls": {
    params: {};
  };
  "/api/liquid_glass_config": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/api/search": {
    params: {};
  };
  "/api/search_files": {
    params: {};
  };
  "/api/imdb_search": {
    params: {};
  };
  "/api/imdb_meta": {
    params: {};
  };
  "/api/image_proxy": {
    params: {};
  };
  "/api/tv_show": {
    params: {};
  };
  "/api/download": {
    params: {};
  };
  "/api/torrents": {
    params: {};
  };
  "/api/torrent/pause": {
    params: {};
  };
  "/api/torrent/resume": {
    params: {};
  };
  "/api/torrent/recheck": {
    params: {};
  };
  "/api/torrent/reannounce": {
    params: {};
  };
  "/api/torrent_files": {
    params: {};
  };
  "/api/torrent_pieces": {
    params: {};
  };
  "/api/download_file": {
    params: {};
  };
  "/api/settings": {
    params: {};
  };
  "/api/qb_status": {
    params: {};
  };
  "/api/app_version": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search" | "/library" | "/settings" | "/torrents" | "/debug/liquid-glass" | "/debug/liquid-glass-controls" | "/api/liquid_glass_config" | "/.well-known/appspecific/com.chrome.devtools.json" | "/api/search" | "/api/search_files" | "/api/imdb_search" | "/api/imdb_meta" | "/api/image_proxy" | "/api/tv_show" | "/api/download" | "/api/torrents" | "/api/torrent/pause" | "/api/torrent/resume" | "/api/torrent/recheck" | "/api/torrent/reannounce" | "/api/torrent_files" | "/api/torrent_pieces" | "/api/download_file" | "/api/settings" | "/api/qb_status" | "/api/app_version";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "./routes/library.tsx": {
    id: "routes/library";
    page: "/library";
  };
  "./routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "./routes/torrents.tsx": {
    id: "routes/torrents";
    page: "/torrents";
  };
  "./routes/debug.liquid-glass.tsx": {
    id: "routes/debug.liquid-glass";
    page: "/debug/liquid-glass";
  };
  "./routes/debug.liquid-glass-controls.tsx": {
    id: "routes/debug.liquid-glass-controls";
    page: "/debug/liquid-glass-controls";
  };
  "./routes/api.liquid_glass_config.ts": {
    id: "routes/api.liquid_glass_config";
    page: "/api/liquid_glass_config";
  };
  "./routes/well-known.chrome-devtools.ts": {
    id: "routes/well-known.chrome-devtools";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "./routes/api.search.ts": {
    id: "routes/api.search";
    page: "/api/search";
  };
  "./routes/api.search_files.ts": {
    id: "routes/api.search_files";
    page: "/api/search_files";
  };
  "./routes/api.imdb_search.ts": {
    id: "routes/api.imdb_search";
    page: "/api/imdb_search";
  };
  "./routes/api.imdb_meta.ts": {
    id: "routes/api.imdb_meta";
    page: "/api/imdb_meta";
  };
  "./routes/api.image_proxy.ts": {
    id: "routes/api.image_proxy";
    page: "/api/image_proxy";
  };
  "./routes/api.tv_show.ts": {
    id: "routes/api.tv_show";
    page: "/api/tv_show";
  };
  "./routes/api.download.ts": {
    id: "routes/api.download";
    page: "/api/download";
  };
  "./routes/api.torrents.ts": {
    id: "routes/api.torrents";
    page: "/api/torrents";
  };
  "./routes/api.torrent.pause.ts": {
    id: "routes/api.torrent.pause";
    page: "/api/torrent/pause";
  };
  "./routes/api.torrent.resume.ts": {
    id: "routes/api.torrent.resume";
    page: "/api/torrent/resume";
  };
  "./routes/api.torrent.recheck.ts": {
    id: "routes/api.torrent.recheck";
    page: "/api/torrent/recheck";
  };
  "./routes/api.torrent.reannounce.ts": {
    id: "routes/api.torrent.reannounce";
    page: "/api/torrent/reannounce";
  };
  "./routes/api.torrent_files.ts": {
    id: "routes/api.torrent_files";
    page: "/api/torrent_files";
  };
  "./routes/api.torrent_pieces.ts": {
    id: "routes/api.torrent_pieces";
    page: "/api/torrent_pieces";
  };
  "./routes/api.download_file.ts": {
    id: "routes/api.download_file";
    page: "/api/download_file";
  };
  "./routes/api.settings.ts": {
    id: "routes/api.settings";
    page: "/api/settings";
  };
  "./routes/api.qb_status.ts": {
    id: "routes/api.qb_status";
    page: "/api/qb_status";
  };
  "./routes/api.app_version.ts": {
    id: "routes/api.app_version";
    page: "/api/app_version";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/./routes/_index.tsx");
  "routes/search": typeof import("./app/./routes/search.tsx");
  "routes/library": typeof import("./app/./routes/library.tsx");
  "routes/settings": typeof import("./app/./routes/settings.tsx");
  "routes/torrents": typeof import("./app/./routes/torrents.tsx");
  "routes/debug.liquid-glass": typeof import("./app/./routes/debug.liquid-glass.tsx");
  "routes/debug.liquid-glass-controls": typeof import("./app/./routes/debug.liquid-glass-controls.tsx");
  "routes/api.liquid_glass_config": typeof import("./app/./routes/api.liquid_glass_config.ts");
  "routes/well-known.chrome-devtools": typeof import("./app/./routes/well-known.chrome-devtools.ts");
  "routes/api.search": typeof import("./app/./routes/api.search.ts");
  "routes/api.search_files": typeof import("./app/./routes/api.search_files.ts");
  "routes/api.imdb_search": typeof import("./app/./routes/api.imdb_search.ts");
  "routes/api.imdb_meta": typeof import("./app/./routes/api.imdb_meta.ts");
  "routes/api.image_proxy": typeof import("./app/./routes/api.image_proxy.ts");
  "routes/api.tv_show": typeof import("./app/./routes/api.tv_show.ts");
  "routes/api.download": typeof import("./app/./routes/api.download.ts");
  "routes/api.torrents": typeof import("./app/./routes/api.torrents.ts");
  "routes/api.torrent.pause": typeof import("./app/./routes/api.torrent.pause.ts");
  "routes/api.torrent.resume": typeof import("./app/./routes/api.torrent.resume.ts");
  "routes/api.torrent.recheck": typeof import("./app/./routes/api.torrent.recheck.ts");
  "routes/api.torrent.reannounce": typeof import("./app/./routes/api.torrent.reannounce.ts");
  "routes/api.torrent_files": typeof import("./app/./routes/api.torrent_files.ts");
  "routes/api.torrent_pieces": typeof import("./app/./routes/api.torrent_pieces.ts");
  "routes/api.download_file": typeof import("./app/./routes/api.download_file.ts");
  "routes/api.settings": typeof import("./app/./routes/api.settings.ts");
  "routes/api.qb_status": typeof import("./app/./routes/api.qb_status.ts");
  "routes/api.app_version": typeof import("./app/./routes/api.app_version.ts");
};