// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/torrents": {
    params: {};
  };
  "/api/search": {
    params: {};
  };
  "/api/download": {
    params: {};
  };
  "/api/torrents": {
    params: {};
  };
  "/api/torrent/pause": {
    params: {};
  };
  "/api/torrent/resume": {
    params: {};
  };
  "/api/torrent/recheck": {
    params: {};
  };
  "/api/torrent/reannounce": {
    params: {};
  };
  "/api/torrent_files": {
    params: {};
  };
  "/api/download_file": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search" | "/torrents" | "/api/search" | "/api/download" | "/api/torrents" | "/api/torrent/pause" | "/api/torrent/resume" | "/api/torrent/recheck" | "/api/torrent/reannounce" | "/api/torrent_files" | "/api/download_file";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "./routes/torrents.tsx": {
    id: "routes/torrents";
    page: "/torrents";
  };
  "./routes/api.search.ts": {
    id: "routes/api.search";
    page: "/api/search";
  };
  "./routes/api.download.ts": {
    id: "routes/api.download";
    page: "/api/download";
  };
  "./routes/api.torrents.ts": {
    id: "routes/api.torrents";
    page: "/api/torrents";
  };
  "./routes/api.torrent.pause.ts": {
    id: "routes/api.torrent.pause";
    page: "/api/torrent/pause";
  };
  "./routes/api.torrent.resume.ts": {
    id: "routes/api.torrent.resume";
    page: "/api/torrent/resume";
  };
  "./routes/api.torrent.recheck.ts": {
    id: "routes/api.torrent.recheck";
    page: "/api/torrent/recheck";
  };
  "./routes/api.torrent.reannounce.ts": {
    id: "routes/api.torrent.reannounce";
    page: "/api/torrent/reannounce";
  };
  "./routes/api.torrent_files.ts": {
    id: "routes/api.torrent_files";
    page: "/api/torrent_files";
  };
  "./routes/api.download_file.ts": {
    id: "routes/api.download_file";
    page: "/api/download_file";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/./routes/_index.tsx");
  "routes/search": typeof import("./app/./routes/search.tsx");
  "routes/torrents": typeof import("./app/./routes/torrents.tsx");
  "routes/api.search": typeof import("./app/./routes/api.search.ts");
  "routes/api.download": typeof import("./app/./routes/api.download.ts");
  "routes/api.torrents": typeof import("./app/./routes/api.torrents.ts");
  "routes/api.torrent.pause": typeof import("./app/./routes/api.torrent.pause.ts");
  "routes/api.torrent.resume": typeof import("./app/./routes/api.torrent.resume.ts");
  "routes/api.torrent.recheck": typeof import("./app/./routes/api.torrent.recheck.ts");
  "routes/api.torrent.reannounce": typeof import("./app/./routes/api.torrent.reannounce.ts");
  "routes/api.torrent_files": typeof import("./app/./routes/api.torrent_files.ts");
  "routes/api.download_file": typeof import("./app/./routes/api.download_file.ts");
};